call plug#begin('~/.vim/plugged')
Plug 'mhinz/vim-grepper'
Plug 'ctrlpvim/ctrlp.vim'
call plug#end()

syntax enable

set number 
set expandtab
set tabstop=2et shiftwidth=2
set backspace=2
set autoindent
set background=light
set nobackup
set nowritebackup
set noswapfile
set noundofile

colorscheme=ron

let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
